
-- 增加限制登录终端的开关
INSERT INTO `DEV_CONFIG` (`ID`, `TENANT_ID`, `CONFIG_KEY`, `CONFIG_VALUE`, `CATEGORY`, `REMARK`, `SORT_CODE`, `EXT_JSON`, `DELETE_FLAG`, `CREATE_TIME`, `CREATE_USER`, `UPDATE_TIME`, `UPDATE_USER`) VALUES ('1554740179362967461', '-1', 'FAST_TERMINAL_LIMIT_OPEN', 'false', 'SYS_BASE', '登录终端限制开关', 7, NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);