kind: Deployment
apiVersion: apps/v1
metadata:
  name: $APP_NAME
  namespace: $KUBE_NAMESPACE
  labels:
    app: $APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
      app.kubernetes.io/name: $APP_NAME
      app.kubernetes.io/version: v1
      version: '1'
  template:
    metadata:
      labels:
        app: $APP_NAME
        app.kubernetes.io/name: $APP_NAME
        app.kubernetes.io/version: v1
        version: '1'
    spec:
      containers:
        - name: $APP_NAME
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$TIME_VERSION
          ports:
            - name: http-80
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: $QKE_DOCKER_CREDENTICAL
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
